# Generated by Django 2.0.10 on 2019-03-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190301_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
