# Generated by Django 2.0.10 on 2019-03-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190303_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='inReadingList',
            field=models.BooleanField(default=False),
        ),
    ]
