# Generated by Django 2.0.10 on 2019-03-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_link_inreadinglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='creator',
            new_name='owner',
        ),
    ]
