# Generated by Django 2.0.10 on 2019-03-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190306_1917'),
        ('users', '0016_auto_20190304_0258'),
    ]

    operations = [
    ]
