# Generated by Django 2.0.10 on 2019-03-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='collection',
        ),
    ]
