# Generated by Django 2.0.10 on 2019-03-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190319_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='owner',
            new_name='author',
        ),
    ]
